# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - arclogicapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Package logic
      run: (mkdir -p ../output; zip -r ../output/logic.zip .)
  #  - name: Upload app zip package
  #    uses: actions/upload-artifact@v2
  #    with:
  #      name: logic
  #      path: ./output/
  #     retention-days: 1

  

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.4.4
      id: fa
      with:
        app-name: 'arclogicapp'
        slot-name: 'production'
        package: '../output/logic.zip'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d0d7b1c6460245a1a65a9248a861743a }}
